name: OS Patching with Ansible
 
on:
 push:
 branches:
 - main
 
jobs:
 patch-servers:
 runs-on: ubuntu-latest
 
 steps:
 - name: Checkout Repository
 uses: actions/checkout@v3
 
 - name: List Repository Files
 run: ls -lah # Debugging step to verify if the playbook exists
 
 - name: present working directory
 run: pwd # Debugging step to verify if the playbook exists
 
